### PR TITLE
docs: 📚️ update commands to pnpm for peterportal

### PR DESCRIPTION
**Pull request by js0mmer**
Updated PeterPortal docs to:
* Replace npm with pnpm
* Add an instruction for installing pnpm

### CODE REVIEW

**Review by CadenLee2 — APPROVED** [review]
Documentation changes look good--all updated commands/steps are correct and match what we currently use

**Review by Awesome-E — COMMENTED** [review]
It'd be good to add a note that you may need to do `sudo npm install -g pnpm` since it's a global package. This mostly applies to Mac, but it is something we also ran into during onboarding

**Comment by alexanderl19** [comment]
> It'd be good to add a note that you may need to do `sudo npm install -g pnpm` since it's a global package. This mostly applies to Mac, but it is something we also ran into during onboarding

I'll merge for the time being, but we could have a more centralized page covering pnpm since most of our projects use it anyways. Also I remember there being some issues with being able to merge PRs. Is that still the case?

**Comment by js0mmer** [comment]
No, I can merge now.

**Pull request merged**
